[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
#public key of the deployed program
mostro_program = "CHHG6MRJ8EBenBeUk3xM1FJGQgwarK8qsJ8QGk2mo9Wd"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://api.devnet.solana.com" 
#signer wallet - private key that pays for transactions, deployments, and fees.
wallet = "~/.config/solana/id.json" 

[scripts]
test = "cargo test-bpf"
