
[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
mostro_program = "4oXq5TDyEmXhqJ39sguoPsq5DKmouubkz5ePjBbBYp7Q"

[provider]
cluster = "http://127.0.0.1:8899" 
wallet = "~/.config/solana/id.json"

#[scripts]
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
